export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#919191",
        "on-error": "#690005",
        "surface": "#131313",
        "on-primary": "#1a1c1c",
        "primary-fixed-dim": "#454747",
        "on-error-container": "#ffdad6",
        "on-surface": "#e2e2e2",
        "on-primary-container": "#000000",
        "on-surface-variant": "#c6c6c6",
        "on-background": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#c8c6c5",
        "background": "#131313",
        "tertiary-fixed": "#5d5f5f",
        "primary-container": "#d4d4d4",
        "on-secondary": "#1c1b1b",
        "surface-bright": "#393939",
        "on-tertiary": "#1a1c1c",
        "on-tertiary-fixed": "#ffffff",
        "primary": "#ffffff",
        "surface-tint": "#c6c6c7",
        "surface-container-low": "#1b1b1b",
        "tertiary-fixed-dim": "#454747",
        "error": "#ffb4ab",
        "tertiary-container": "#909191",
        "surface-container": "#1f1f1f",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#3c3b3b",
        "surface-variant": "#353535",
        "on-tertiary-container": "#000000",
        "primary-fixed": "#5d5f5f",
        "inverse-primary": "#5d5f5f",
        "tertiary": "#e2e2e2",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "secondary": "#c8c6c5",
        "secondary-fixed-dim": "#adabaa",
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed": "#ffffff",
        "secondary-container": "#474746",
        "surface-container-lowest": "#0e0e0e",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#e2e2e2",
        "outline-variant": "#474747",
        "on-secondary-container": "#e5e2e1",
        "surface-container-highest": "#353535",
        "on-secondary-fixed": "#1c1b1b",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
